#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#


library(shiny)
library(networkD3)
library(Recca)
library(pins)
library(leaflet)
library(shinythemes)
library(networkD3)
suppressWarnings(library(rworldmap))
library(reshape2)
library(ggplot2)
library(googleway)
library(dplyr)
library(readxl)
library(bslib)
library(thematic)
thematic::thematic_shiny(font = "auto")


pinboard_folder <- file.path("D:/Energy Visualizer/data")
pinboard <- pins::board_folder(pinboard_folder, versioned = TRUE)
agg_eta_pfu_df <- pins::pin_read(board = pinboard, name = "agg_eta_pfu", version = "20230619T051304Z-f653c")
psut_df <- pins::pin_read(board = pinboard, name = "psut", version = "20230915T185731Z-c48a0")

country_names <- read_excel("C:/Users/Keren/Documents/Shiny_app/Data/Country_Concordance_Full.xlsx")
iso_codes <- data.frame(iso3_code_full = country_names$ISO3C.code, full_name = country_names$FAO.name)
iso_codes <- iso_codes[complete.cases(iso_codes), ]

# Extract unique values from psut_df
unique_countries <- unique(psut_df[["Country"]])

# Create a data frame with unique countries
unique_countries_df <- data.frame(iso3_code_full = unique_countries)

joined_names <- dplyr::left_join(unique_countries_df, iso_codes, by = "iso3_code_full")

worldMap <- suppressWarnings(getMap())

page1 <- tabPanel(
  title = "Global Map",
  titlePanel("Background"),
  p("The Energy Visualizer shows datasets for primary, final, and useful energy and exergy generated by a global network of researchers.  Various datasets cover hundreds of years of global and country-level information.  Two energy and exergy datasets are available:

* A long-run dataset covering 1800 - 2020 at the world level. << references here >>
* A short-run dataset covering 1960 - 2020 for select countries and 1971 for 155 countries. <<Reference the CL-PFU database paper here >> "),
  h3("Interactive Map"),
  sidebarLayout(
    sidebarPanel(
      selectInput("countrya", "Select a Country",
                  choices = joined_names$full_name,
                  selected = joined_names$full_name),
      sliderInput("yeara", "Select a Year",
                  min = min(psut_df["Year"]), max = max(psut_df["Year"]), value = min(psut_df["Year"]), step = 1, 
                  animate = animationOptions(interval = 2000, loop = TRUE, playButton = NULL, pauseButton = NULL), sep=""),
      htmlOutput("sankeyPlot", inline = FALSE)
      
    ),
    mainPanel(
      
      
      plotOutput("mapPlot", height = "500", width = "900")
    )
  )
)

ago1971 <- psut_df |> dplyr::filter(Country == psut_df["Country"], Year == psut_df["Year"])
R_ago_1971 <- ago1971$R[[1]] |> unlist() |> as.matrix()
ago1971 <- psut_df |> dplyr::filter(Country == psut_df["Country"], Year == psut_df["Year"])
Y_ago_1971 <- ago1971$Y[[1]] |> unlist() |> as.matrix()

page2 <- tabPanel(
  title ="In-depth View",
  tags$h3("Efficiency Graph"),
  sidebarLayout(
    position = "right",
    sidebarPanel(
      style = "position: sticky; top: 0px;",
      selectInput("countryb", "Select a Country",
                  choices = joined_names$full_name,
                  selected = joined_names$full_name),
      radioButtons("ieamwa", "Select IEAMW:",
                   choices = c("IEA", "MW", "Both"),
                   selected = "IEA"),
       sliderInput("yearb", "Select a Year",
                    min = min(psut_df["Year"]), max = max(psut_df["Year"]), value = min(psut_df["Year"]), step = 1, sep=""),
        radioButtons("categorya", "Select Category:",
                                       choices = c("Final demand sector", "Resource sector", "Final demand energy carriers", "Resource energy carriers"),
                                       selected = "Final demand sector"),
        radioButtons("last.stagea", "Select Last Stage:",
                                       choices = c("Final", "Useful"),
                                       selected = "Final"),
        radioButtons("energy.typea", "Select Energy Type:",
                                       choices = c("E", "X"),
                                       selected = "E"),
        selectizeInput("optionsa",
                       label = "Select Options:",
                       choices = c(colnames(Y_ago_1971),rownames(R_ago_1971),colnames(R_ago_1971),rownames(Y_ago_1971)),
                       multiple = TRUE),

    ),
  mainPanel(
    fluidPage(

      wellPanel(
        fluidRow(
          h4("Aggregated Efficiencies"),
          column(width = 12, plotOutput("Plot"))
        )
      ),
      tags$br(),
      fluidRow(
        HTML("<h3>Sankey Diagram</h3>"),
        htmlOutput("sankeyPlot2", inline = FALSE),
        verbatimTextOutput("eff7_output")
      )
    )
  )
)
)

page3 <- tabPanel(
  title ="Country Comparison",
  tags$h1("Sankey"),

  sidebarLayout(
  position = "right",
    sidebarPanel(
      style = "position: sticky; top: 0px;",
      radioButtons("category", "Select Category:",
                   choices = c("Final demand sector", "Resource sector", "Final demand energy carriers", "Resource energy carriers"),
                   selected = "Final demand sector"),

      radioButtons("last.stage", "Select Last Stage:",
                   choices = c("Final", "Useful"),
                   selected = "Final"),
      radioButtons("energy.type", "Select Energy Type:",
                   choices = c("E", "X"),
                   selected = "E"),
      radioButtons("ieamw", "Select IEAMW:",
                   choices = c("IEA", "MW", "Both"),
                   selected = "IEA"),
      selectizeInput("options",label = "Select Options:",
                  choices = c(colnames(Y_ago_1971), rownames(R_ago_1971), colnames(R_ago_1971), rownames(Y_ago_1971)),
                  multiple = TRUE)

    ),
  mainPanel(
    fixedRow(
      fluidRow(
        column(width = 3, selectInput("country2", "Select a Country",
                                      choices = joined_names$full_name,
                                      selected = joined_names$full_name)),
        column(width = 7, sliderInput("year2", "Select a Year",
                    min = min(psut_df["Year"]), max = max(psut_df["Year"]), value = min(psut_df["Year"]), step = 1, sep="")),
      ),
      htmlOutput("sankeyPlot3",inline = TRUE),
      verbatimTextOutput("eff8_output")),

    tags$br(),

    fixedRow(
      column(width = 3, selectInput("country3", "Select a Country",
                                    choices = joined_names$full_name,
                                    selected = joined_names$full_name)),
      column(width = 7, sliderInput("year3", "Select a Year",
                  min = min(psut_df["Year"]), max = max(psut_df["Year"]), value = min(psut_df["Year"]), step = 1, sep="")),

      htmlOutput("sankeyPlot4",inline = TRUE),
      verbatimTextOutput("eff9_output")

   )
  )
 )
)

page3 <- tabPanel(
  title ="Country Comparison",
  tags$h1("Sankey"),
  mainPanel(
    fixedRow(
      fluidRow(
        column(width = 3, selectInput("country2", "Select a Country",
                                      choices = joined_names$full_name,
                                      selected = joined_names$full_name)),
        column(width = 7, sliderInput("year2", "Select a Year",
                    min = min(psut_df["Year"]), max = max(psut_df["Year"]), value = min(psut_df["Year"]), step = 1, sep="")),




        column(width=2,radioButtons("category", "Select Category:",
                                    choices = c("Final demand sector", "Resource sector", "Final demand energy carriers", "Resource energy carriers"),
                                    selected = "Final demand sector")),


        column(width=2,radioButtons("last.stage", "Select Last Stage:",
                                    choices = c("Final", "Useful"),
                                    selected = "Final")),

        column(width=2,radioButtons("energy.type", "Select Energy Type:",
                                    choices = c("E", "X"),
                                    selected = "E")),


        column(width=2,radioButtons("ieamw", "Select IEAMW:",
                                    choices = c("IEA", "MW", "Both"),
                                    selected = "IEA")),

        column(width=2,selectizeInput("options",
                                      label = "Select Options:",
                                      choices = c(colnames(Y_ago_1971), rownames(R_ago_1971), colnames(R_ago_1971), rownames(Y_ago_1971)),
                                      multiple = TRUE))
      ),
      htmlOutput("sankeyPlot3",inline = TRUE),
      verbatimTextOutput("eff8_output")),

    tags$br(),

    fixedRow(
      column(width = 3, selectInput("country3", "Select a Country",
                                    choices = joined_names$full_name,
                                    selected = joined_names$full_name)),
       column(width = 7, sliderInput("year3", "Select a Year",
                  min = min(psut_df["Year"]), max = max(psut_df["Year"]), value = min(psut_df["Year"]), step = 1, sep="")),

      htmlOutput("sankeyPlot4",inline = TRUE),
      verbatimTextOutput("eff9_output")

    )
  )
)


ui <- navbarPage(
  title = "Energy Visualizer",
  theme = bs_theme(bootswatch = "flatly"),
  page1,
  page2,
  page3
)





# Define server logic required to draw a histogram
server <- function(input, output, session) {

  selected_country <- reactiveVal(NULL)
  selected_year <- reactiveVal(NULL)

  observeEvent(input$countrya, {
    selected_country(input$countrya)
  })

  observeEvent(input$countryb, {
    selected_country(input$countryb)
  })

  observe({
    updateSelectInput(session, "countrya", selected = selected_country())
    updateSelectInput(session, "countryb", selected = selected_country())
  })

  observeEvent(input$yeara, {
    selected_year(input$yeara)
  })

  observeEvent(input$yearb, {
    selected_year(input$yearb)
  })

  observe({
    updateSelectInput(session, "yeara", selected = selected_year())
    updateSelectInput(session, "yearb", selected = selected_year())
  })

  fulla <- reactive({
    egg <- joined_names$iso3_code_full[joined_names$full_name %in% selected_country()]
    return(egg)
  })

  #matrices for regular sankeys
  data1 <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulla(), Year == selected_year())
    R_ago_1971 <- ago1971$R[[1]] |> unlist() |> as.matrix()
    return(R_ago_1971)
  })

  data2 <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulla(), Year == selected_year())
    U_ago_1971 <- ago1971$U[[1]] |> unlist() |> as.matrix()
    return(U_ago_1971)
  })

  data3 <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulla(), Year == selected_year())
    V_ago_1971 <- ago1971$V[[1]] |> unlist() |> as.matrix()
    return(V_ago_1971)
  })

  data4 <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulla(), Year == selected_year())
    Y_ago_1971 <- ago1971$Y[[1]] |> unlist() |> as.matrix()
    return(Y_ago_1971)
  })

  #matrices for slices
  #New sankey made



  data5 <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulla(), Year == input$year2)
    R_ago_1971 <- ago1971$R[[1]] |> unlist() |> as.matrix()
    return(R_ago_1971)
  })

  data6 <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulla(), Year == input$year2)
    U_ago_1971 <- ago1971$U[[1]] |> unlist() |> as.matrix()
    return(U_ago_1971)
  })

  data7 <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulla(), Year == input$year2)
    V_ago_1971 <- ago1971$V[[1]] |> unlist() |> as.matrix()
    return(V_ago_1971)
  })

  data8 <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulla(), Year == input$year2)
    Y_ago_1971 <- ago1971$Y[[1]] |> unlist() |> as.matrix()
    return(Y_ago_1971)
  })



  #Faceted efficiency graphs
  eff7 <- reactive({
    agg_eta_pfu_df2 <- melt(agg_eta_pfu_df, id = c("Country", "Method", "Energy.type", "Year", "IEAMW", "Chopped.mat", "Chopped.var", "Product.aggregation", "Industry.aggregation", "GrossNet","EX.p", "EX.f", "EX.u")
    )

    agg_eta_pu_all_continents <- agg_eta_pfu_df2 |>
      dplyr::filter(Country == fulla(),
                    Method == "PCM",
                    Year >= 1971,
                    IEAMW == input$ieamwa,
                    Chopped.mat == "None",
                    Chopped.var == "None",
                    Product.aggregation == "Specified",
                    Industry.aggregation == "Specified",
                    GrossNet == "Gross"
      )
    return(agg_eta_pu_all_continents)
  })
  # second page sankey
  eff7a <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulla(), Year == input$yearb, IEAMW == input$ieamwa, Last.stage == input$last.stagea, Energy.type == input$energy.typea)
    R_ago_1971 <- ago1971$R[[1]] |> unlist() |> as.matrix()
    Y_ago_1971 <- ago1971$Y[[1]] |> unlist() |> as.matrix()

    observe({
      updateSelectInput(session, "optionsa",
                        choices = getOptions(input$categorya))
    })

    getOptions <- function(category) {
      if (category == "Final demand sector") {
        return(unique(colnames(Y_ago_1971)))
      } else if (category == "Resource sector") {
        return(unique(rownames(R_ago_1971)))
      } else if (category == "Final demand energy carriers") {
        return(unique(rownames(Y_ago_1971)))
      } else {
        return(unique(colnames(R_ago_1971)))
      }
    }

  })
  eff7b <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulla(), Year == input$yearb, IEAMW == input$ieamwa, Last.stage == input$last.stagea, Energy.type == input$energy.typea)
    return(ago1971)
  })

  fulli <- reactive({
    egg <- joined_names$iso3_code_full[joined_names$full_name %in% input$country2]
    return(egg)
  })

  fulle <- reactive({
    egg <- joined_names$iso3_code_full[joined_names$full_name %in% input$country3]
    return(egg)
  })

  # third page sankey 1st sankey
  eff8 <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulli(), Year == input$year2, IEAMW == input$ieamw, Last.stage == input$last.stage, Energy.type == input$energy.type)
    R_ago_1971 <- ago1971$R[[1]] |> unlist() |> as.matrix()
    Y_ago_1971 <- ago1971$Y[[1]] |> unlist() |> as.matrix()

    ago19711 <- psut_df |> dplyr::filter(Country == fulle(), Year == input$year3, IEAMW == input$ieamw, Last.stage == input$last.stage, Energy.type == input$energy.type)
    R_ago_1972 <- ago19711$R[[1]] |> unlist() |> as.matrix()
    Y_ago_1972 <- ago19711$Y[[1]] |> unlist() |> as.matrix()

    observe({
      updateSelectInput(session, "options",
                        choices = getOptions(input$category))
    })

    getOptions <- function(category) {
      if (category == "Final demand sector") {
        list3 <- intersect(colnames(Y_ago_1971), colnames(Y_ago_1972))
        return(list3)


      } else if (category == "Resource sector") {
        list3 <- intersect(rownames(R_ago_1971), rownames(R_ago_1972))
        return(list3)
      } else if (category == "Final demand energy carriers") {
        list3 <- intersect(rownames(Y_ago_1971), rownames(Y_ago_1972))

        return(list3)
      } else {
        list3 <- intersect(colnames(R_ago_1971), colnames(R_ago_1972))
        return(list3)
      }
    }

  })
  # # third page saneky 2nd sankey
  # eff9 <- reactive({
  #   ago1971 <- psut_df |> dplyr::filter(Country == input$country3, Year == input$year3, IEAMW == input$ieamw, Last.stage == input$last.stage, Energy.type == input$energy.type)
  #   R_ago_1971 <- ago1971$R[[1]] |> unlist() |> as.matrix()
  #   Y_ago_1971 <- ago1971$Y[[1]] |> unlist() |> as.matrix()
  #
  #
  #   observe({
  #     updateSelectInput(session, "options",
  #                       choices = getOptions(input$category))
  #   })
  #
  #   getOptions <- function(category) {
  #     if (category == "Final demand sector") {
  #       return(unique(colnames(Y_ago_1971)))
  #     } else if (category == "Resource sector") {
  #       return(unique(rownames(R_ago_1971)))
  #     } else if (category == "Final demand energy carriers") {
  #       return(unique(rownames(Y_ago_1971)))
  #     } else {
  #       return(unique(colnames(R_ago_1971)))
  #     }
  #   }
  #
  # })
  # third page sankey 1st sankey
  eff10 <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulli(), Year == input$year2, IEAMW == input$ieamw, Last.stage == input$last.stage, Energy.type == input$energy.type)
    return(ago1971)
  })
  # third page sankey 2nd sankey
  eff11 <- reactive({
    ago1971 <- psut_df |> dplyr::filter(Country == fulle(), Year == input$year3, IEAMW == input$ieamw, Last.stage == input$last.stage, Energy.type == input$energy.type)
    return(ago1971)
  })



  code <- reactive({
    egg <- joined_names$iso3_code_full[joined_names$full_name %in% input$countrya]
    return(egg)
  })

  #Interactive map view
  concode <- reactive({
    if (code() == 'CHNM') {
      return('CHN')
    } else if (code() == 'OAFR') {
      return(c('SHN','BFA','BDI','CPV','CAF','TCD','COM','DJI','GMB','GIN','GNB','LSO','LBR','MWI','MLI','MRT','MYT','STP','REU','SYC','SLE','SOM'))
    } else if (code() == 'OASI') {
      return(c('AFG','BTN','CXR','CCK','IOT','MAC','MDV','PSE'))
    } else if (code() == 'OAMR') {
      return(C('CHL','GUF','PER'))
    } else {
      return(code())
    }
  })


  country_map <- reactive({
    # Get the ISO 3166-1 alpha-3 country code for the input acronym
    country_val <- concode()
    iso3_code <- countrycode::countrycode(sourcevar = country_val, origin = "iso3c", destination = "iso3c")


    # Filter for the specific country
    if (input$countrya == "World") {
      # Return the entire worldMap dataset without filtering
      return(worldMap)
    } else {
      subset(worldMap, ISO3 %in% iso3_code)
    }
  })


  # Render the map plot
  output$mapPlot <- renderPlot({
    # Plot the world map
    ggplot() +
      geom_polygon(data = worldMap, aes(x = long, y = lat, group = group), fill = "lightgrey", color = "black") +
      geom_polygon(data = country_map(), aes(x = long, y = lat, group = group), fill = "#2C3E50", color = "black") +
      coord_fixed() +
      labs(title = paste("Map of", input$countrya)) +
      theme_minimal()
  })


  #Efficiency graph representation
  output$Plot <- renderPlot({
    eff7() |>
      ggplot2::ggplot(mapping = ggplot2::aes(x = Year,
                                             y = value),
                      colour = Country,
                      linetype = Country,
                      linewidth = Country) +
      ggplot2::geom_line() +
      ggplot2::scale_x_continuous(breaks = c(1980, 2000, 2020)) +
      ggplot2::scale_y_continuous(limits = c(0, 1),
                                  breaks = c(0.0, 0.2, 0.4, 0.6, 0.8, 1),
                                  labels = scales::label_percent(suffix = "")) +
      ggplot2::labs(x = NULL,
                    y = expression("Energy and exergy efficiency ("*eta*") [%]"),
                    colour = NULL,
                    linetype = NULL,
                    linewidth = NULL) +
      ggplot2::facet_grid(rows = ggplot2::vars(variable),
                          cols = ggplot2::vars(Energy.type),
                          labeller = ggplot2::label_parsed) +
      ggplot2::guides(
        colour = ggplot2::guide_legend(
          override.aes = list(linewidth = 1)  # Adjust the size of the line segments in the legend only
        )
      )
  })

  #Sankey portrayal
  # second page saneky
  # second page saneky
  output$sankeyPlot <- renderUI({Recca::make_sankey(R = data1(),
                                                    U = data2(),
                                                    V = data3(),
                                                    Y = data4(), nodeWidth = 10, nodePadding = 7, width = "auto", height = "400")})
  # first page sankey
  output$sankeyPlot2 <- renderUI({Recca::make_sankey(R = data1(),
                                                     U = data2(),
                                                     V = data3(),
                                                     Y = data4())})
  # third page sankey 1st
  output$sankeyPlot3 <- renderUI({Recca::make_sankey(R = data5(),
                                                     U = data6(),
                                                     V = data7(),
                                                     Y = data8())})
  # third page sankey 2nd
  output$sankeyPlot4 <- renderUI({Recca::make_sankey(R = data9(),
                                                     U = data10(),
                                                     V = data11(),
                                                     Y = data12())})
  # page 2
  output$eff7_output <- renderPrint({
    eff7a()
  })

  # page 3 1st
  output$eff8_output <- renderPrint({
    eff8()
  })
  # page 3 2nd
  # output$eff9_output <- renderPrint({
  #   eff9()
  # })
  do_chop <- function(rowdf, category, selectedOptions){
    #Professor paste logic here
    if (is.null(selectedOptions)) {
      # No options selected,
      # so no reason to do chops.
      return(rowdf)
    }

    if (category == "Final demand sector") {
      # User wants to isolate columns from the Y matrix
      out <- rowdf |>
        Recca::calc_io_mats(direction = "upstream") |>
        dplyr::mutate(
          Y_prime = matsbyname::select_cols_byname(Y, RCLabels::make_or_pattern(selectedOptions))
        ) |>
        Recca::new_Y()
    } else if (category == "Resource sector") {
      # User wants to isolate rows from the R matrix
      out <- rowdf |>
        Recca::calc_io_mats(direction = "downstream") |>
        dplyr::mutate(
          R_prime = matsbyname::select_rows_byname(R, RCLabels::make_or_pattern(selectedOptions))
        ) |>
        Recca::new_R_ps()
    } else if (category == "Final demand energy carriers") {
      # User wants to isolate rows from the Y matrix
      out <- rowdf |>
        Recca::calc_io_mats(direction = "upstream") |>
        dplyr::mutate(
          Y_prime = matsbyname::select_rows_byname(Y, RCLabels::make_or_pattern(selectedOptions))
        ) |>
        Recca::new_Y()
    } else if (category == "Resource energy carriers") {
      # User wants to isolate columns from the R matrix
      out <- rowdf |>
        Recca::calc_io_mats(direction = "downstream") |>
        dplyr::mutate(
          R_prime = matsbyname::select_cols_byname(R, RCLabels::make_or_pattern(selectedOptions))
        ) |>
        Recca::new_R_ps()
    } else {
      # The category is unknown.
      stop("Unknown category in do_chop()")
    }

    out |>
      dplyr::mutate(
        # Get rid of old (unchopped) versions matrix columns
        R = NULL, U_feed = NULL, U_EIOU = NULL, r_EIOU = NULL, U = NULL, V = NULL, Y = NULL,
        # And eliminate io matrices created by calc_io_mats()
        y = NULL, q = NULL, f = NULL, g = NULL, h = NULL, r = NULL, W = NULL, Z = NULL,
        K = NULL, C = NULL, D = NULL, A = NULL, O = NULL, L_pxp = NULL, L_ixp = NULL,
        Z_feed = NULL, K_feed = NULL, A_feed = NULL, L_ixp_feed = NULL, L_pxp_feed = NULL,
        Z_s = NULL, C_s = NULL, D_s = NULL, D_feed_s = NULL, O_s = NULL, B = NULL, G_pxp = NULL, G_ixp = NULL
      ) |>
      dplyr::rename(
        # Set new names so that the outgoing 1-row data frame
        # has the same columns as the incoming 1-row data frame
        R = R_prime,
        U_feed = U_feed_prime,
        U_EIOU = U_EIOU_prime,
        r_EIOU = r_EIOU_prime,
        U = U_prime,
        V = V_prime,
        Y = Y_prime
      )
  }

  #For page 2 sankey
  #Updated 3/11
  magic_function0 <- reactive({
    rowdf <- eff7b()
    category <- input$categorya
    selectedOptions <- input$optionsa

    result <- do_chop(rowdf, category, selectedOptions)
    return(result)
  })

  data13 <- reactive({
    new_row <- magic_function0()
    R_ago_1971 <- new_row$R[[1]] |> unlist() |> as.matrix()
    return(R_ago_1971)
  })

  data14  <- reactive({
    new_row <- magic_function0()
    U_ago_1971 <- new_row$U[[1]] |> unlist() |> as.matrix()
    return(U_ago_1971)
  })

  data15  <- reactive({
    new_row <- magic_function0()
    V_ago_1971 <- new_row$V[[1]] |> unlist() |> as.matrix()
    return(V_ago_1971)
  })

  data16  <- reactive({
    new_row <- magic_function0()
    Y_ago_1971 <- new_row$Y[[1]] |> unlist() |> as.matrix()
    return(Y_ago_1971)
  })
  output$sankeyPlot2 <- renderUI({Recca::make_sankey(R = data13(),
                                                     U = data14(),
                                                     V = data15(),
                                                     Y = data16())})
  # third page sankey 1st
  magic_function <- reactive({
    rowdf <- eff10()
    category <- input$category
    selectedOptions <- input$options

    result <- do_chop(rowdf, category, selectedOptions)
    return(result)
  })
  data5 <- reactive({
    new_row <- magic_function()
    R_ago_1971 <- new_row$R[[1]] |> unlist() |> as.matrix()
    return(R_ago_1971)
  })
  data6  <- reactive({
    new_row <- magic_function()
    U_ago_1971 <- new_row$U[[1]] |> unlist() |> as.matrix()
    return(U_ago_1971)
  })
  data7  <- reactive({
    new_row <- magic_function()
    V_ago_1971 <- new_row$V[[1]] |> unlist() |> as.matrix()
    return(V_ago_1971)
  })
  data8  <- reactive({
    new_row <- magic_function()
    Y_ago_1971 <- new_row$Y[[1]] |> unlist() |> as.matrix()
    return(Y_ago_1971)
  })

  # third page sankey 2nd sankey
  magic_function2 <- reactive({
    rowdf <- eff11()
    category <- input$category
    selectedOptions <- input$options

    result <- do_chop(rowdf, category, selectedOptions)
    return(result)
  })
  data9 <- reactive({
    new_row <- magic_function2()
    R_ago_1971 <- new_row$R[[1]] |> unlist() |> as.matrix()
    return(R_ago_1971)
  })

  data10  <- reactive({
    new_row <- magic_function2()
    U_ago_1971 <- new_row$U[[1]] |> unlist() |> as.matrix()
    return(U_ago_1971)
  })

  data11  <- reactive({
    new_row <- magic_function2()
    V_ago_1971 <- new_row$V[[1]] |> unlist() |> as.matrix()
    return(V_ago_1971)
  })

  data12  <- reactive({
    new_row <- magic_function2()
    Y_ago_1971 <- new_row$Y[[1]] |> unlist() |> as.matrix()
    return(Y_ago_1971)
  })

  # updated third page sankey 1st
  output$sankeyPlot3 <- renderUI({Recca::make_sankey(R = data5(),
                                                     U = data6(),
                                                     V = data7(),
                                                     Y = data8())})
  # second sankey third page updated
  output$sankeyPlot4 <- renderUI({Recca::make_sankey(R = data9(),
                                                     U = data10(),
                                                     V = data11(),
                                                     Y = data12())})

}

# Run the application
shinyApp( ui,  server)

